node {

    def tool = new Tool(this)

    stage('CleanUp') {
        fileOperations([folderDeleteOperation('')])
    }

    stage('Git') {
        git branch: 'tool', credentialsId: 'ded4ba1f-ac90-483e-aa06-8ce73b1d12ca', url: '${this.params.framework-url}'
    }

    stage('Gradle') {

        dir(tool.getRoot()) {
            tool.createJar()
            tool.runJar()
        }
    }

}

class Tool {

    def pipe
    def mainClass = 'com.tool.automation.core.runner.ToolTestRunner'
    def root = 'tool-tests'

    def params = [
            "url": "${pipe.params.application-url}",
            "excel": "test-input/${pipe.params.suite}/${pipe.params.case}.xlsx"
    ]

    Tool(def pipe) {
        this.pipe = pipe
    }

    void createJar() {
        pipe.bat 'gradle shadowJar'
    }

    String runJar() {
        String paramString = params.collect { k, v -> "-$k \"$v\"" }.join(" ")

        if (getParams().api) {
            paramString = paramString + " -api"
        }
        pipe.bat "java -cp at_tool-1.0.jar ${mainClass} ${paramString}"
    }
}



