package com.epam.ipipeline.testing.model.enums;

public enum TestObjectsType {
    Button_1("1-Button"),
    Checkbox_1("1-Checkbox"),
    Screen_1("1-Screen"),
    Textbox_1("1-Textbox"),
    APIManager,
    Acord,
    Address,
    Alert,
    Attachment,
    Browser,
    Button,
    Case,
    CaseDetails,
    CaseInfo,
    Checkbox,
    ClickWrap,
    ConsumerPortal,
    ControlTest,
    CreateLogin,
    CreditCard,
    CustomSDTest,
    CustomTest,
    Datebox,
    Debug,
    DetailView,
    Dropdown,
    EditTemplate,
    ElementTest,
    ErrorPopUp,
    Esig,
    Grid,
    Group,
    Hyperlink,
    IFrame,
    IGo,
    IgoClientData,
    Illus,
    Image,
    JiraCase,
    MRAS,
    Mailbox,
    ManageTemplates,
    ManageValidationExpressions,
    ManageValuesLists,
    Maskbox,
    Matches,
    NeedsAnalysis,
    NestedPopUp,
    NewTableItemDialog,
    NewTemplateVariableDialog,
    PHS,
    Page,
    Paramed,
    Pdf,
    PipePassTool,
    PolicyNumber,
    PopUp,
    Popover,
    Preview,
    ProductAdminPage,
    RadioButton,
    Report,
    RuleActionCheck,
    RuleEditorTest,
    SDAlert,
    SDColumnsConfig,
    SDConfirm,
    SDControl,
    SDGrid,
    SDGridColumns,
    SDGroup,
    SDPropertyCard,
    SDScreen,
    SDSupplier,
    Screen,
    ScreenDesigner,
    Signature,
    Tab,
    TemplateAdminPage,
    TemplateDialog,
    TextMessage,
    Textbox,
    ValidationExpressionDialog,
    Version,
    Xml;

    private String name;

    TestObjectsType(String name) {
      this.name = name;
    }

    TestObjectsType() {
      this.name = this.name();
    }

    public String getName() {
      return name;
    }
}
